---
collections:
  - name: community.crypto
    version: 2.26.4
  - name: ansible.posix
    version: 2.0.0
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.general
    version: 10.7.0
    source: https://github.com/ansible-collections/community.general.git
    type: git
