---
collections:
  - name: community.crypto
    version: 3.0.3
  - name: ansible.posix
    version: 2.1.0
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.general
    version: 11.1.1
    source: https://github.com/ansible-collections/community.general.git
    type: git
