---
- name: "Create {{ service_name }} dir"
  file:
    path: "{{ docker_compose_path }}"
    state: directory
    mode: 0755

- name: "Add docker-compose.yml"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    mode: 0644
  notify:
    - "Restart {{ service_name }}"

- name: "Add {{ service_name }}.env"
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ docker_compose_path }}/.env"
    mode: 0644

- name: "Install {{ service_name }} service"
  ansible.builtin.template:
    src: "{{ service_name }}.service.j2"
    dest: "/lib/systemd/system/{{ service_name }}.service"
    mode: 0644
  notify:
    - "Restart {{ service_name }}"
